name: micro_dart_proxy_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
   micro_dart_runtime: 
    path: ../micro_dart_runtime

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
