// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'dart:collection';
import 'dart:math' show Random;

const libraryMirror = m.LibraryMirror(
  'dart:collection',
  {},
  {},
  {},
);
