import 'package:flutter/src/services/autofill.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/src/services/text_input.dart';
import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
Map<String,Function> getLibrary(m.MicroDartEngine engine) {
return {
'package:flutter/src/services/autofill.dart@AutofillHints@#as': (m.Scope scope, target)=>()=>target as AutofillHints,
'package:flutter/src/services/autofill.dart@AutofillHints@#is': (m.Scope scope, target)=>()=>target is AutofillHints,
'package:flutter/src/services/autofill.dart@AutofillHints@addressCity': (m.Scope scope)=>AutofillHints.addressCity,
'package:flutter/src/services/autofill.dart@AutofillHints@addressCityAndState': (m.Scope scope)=>AutofillHints.addressCityAndState,
'package:flutter/src/services/autofill.dart@AutofillHints@addressState': (m.Scope scope)=>AutofillHints.addressState,
'package:flutter/src/services/autofill.dart@AutofillHints@birthday': (m.Scope scope)=>AutofillHints.birthday,
'package:flutter/src/services/autofill.dart@AutofillHints@birthdayDay': (m.Scope scope)=>AutofillHints.birthdayDay,
'package:flutter/src/services/autofill.dart@AutofillHints@birthdayMonth': (m.Scope scope)=>AutofillHints.birthdayMonth,
'package:flutter/src/services/autofill.dart@AutofillHints@birthdayYear': (m.Scope scope)=>AutofillHints.birthdayYear,
'package:flutter/src/services/autofill.dart@AutofillHints@countryCode': (m.Scope scope)=>AutofillHints.countryCode,
'package:flutter/src/services/autofill.dart@AutofillHints@countryName': (m.Scope scope)=>AutofillHints.countryName,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardExpirationDate': (m.Scope scope)=>AutofillHints.creditCardExpirationDate,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardExpirationDay': (m.Scope scope)=>AutofillHints.creditCardExpirationDay,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardExpirationMonth': (m.Scope scope)=>AutofillHints.creditCardExpirationMonth,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardExpirationYear': (m.Scope scope)=>AutofillHints.creditCardExpirationYear,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardFamilyName': (m.Scope scope)=>AutofillHints.creditCardFamilyName,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardGivenName': (m.Scope scope)=>AutofillHints.creditCardGivenName,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardMiddleName': (m.Scope scope)=>AutofillHints.creditCardMiddleName,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardName': (m.Scope scope)=>AutofillHints.creditCardName,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardNumber': (m.Scope scope)=>AutofillHints.creditCardNumber,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardSecurityCode': (m.Scope scope)=>AutofillHints.creditCardSecurityCode,
'package:flutter/src/services/autofill.dart@AutofillHints@creditCardType': (m.Scope scope)=>AutofillHints.creditCardType,
'package:flutter/src/services/autofill.dart@AutofillHints@email': (m.Scope scope)=>AutofillHints.email,
'package:flutter/src/services/autofill.dart@AutofillHints@familyName': (m.Scope scope)=>AutofillHints.familyName,
'package:flutter/src/services/autofill.dart@AutofillHints@fullStreetAddress': (m.Scope scope)=>AutofillHints.fullStreetAddress,
'package:flutter/src/services/autofill.dart@AutofillHints@gender': (m.Scope scope)=>AutofillHints.gender,
'package:flutter/src/services/autofill.dart@AutofillHints@givenName': (m.Scope scope)=>AutofillHints.givenName,
'package:flutter/src/services/autofill.dart@AutofillHints@impp': (m.Scope scope)=>AutofillHints.impp,
'package:flutter/src/services/autofill.dart@AutofillHints@jobTitle': (m.Scope scope)=>AutofillHints.jobTitle,
'package:flutter/src/services/autofill.dart@AutofillHints@language': (m.Scope scope)=>AutofillHints.language,
'package:flutter/src/services/autofill.dart@AutofillHints@location': (m.Scope scope)=>AutofillHints.location,
'package:flutter/src/services/autofill.dart@AutofillHints@middleInitial': (m.Scope scope)=>AutofillHints.middleInitial,
'package:flutter/src/services/autofill.dart@AutofillHints@middleName': (m.Scope scope)=>AutofillHints.middleName,
'package:flutter/src/services/autofill.dart@AutofillHints@name': (m.Scope scope)=>AutofillHints.name,
'package:flutter/src/services/autofill.dart@AutofillHints@namePrefix': (m.Scope scope)=>AutofillHints.namePrefix,
'package:flutter/src/services/autofill.dart@AutofillHints@nameSuffix': (m.Scope scope)=>AutofillHints.nameSuffix,
'package:flutter/src/services/autofill.dart@AutofillHints@newPassword': (m.Scope scope)=>AutofillHints.newPassword,
'package:flutter/src/services/autofill.dart@AutofillHints@newUsername': (m.Scope scope)=>AutofillHints.newUsername,
'package:flutter/src/services/autofill.dart@AutofillHints@nickname': (m.Scope scope)=>AutofillHints.nickname,
'package:flutter/src/services/autofill.dart@AutofillHints@oneTimeCode': (m.Scope scope)=>AutofillHints.oneTimeCode,
'package:flutter/src/services/autofill.dart@AutofillHints@organizationName': (m.Scope scope)=>AutofillHints.organizationName,
'package:flutter/src/services/autofill.dart@AutofillHints@password': (m.Scope scope)=>AutofillHints.password,
'package:flutter/src/services/autofill.dart@AutofillHints@photo': (m.Scope scope)=>AutofillHints.photo,
'package:flutter/src/services/autofill.dart@AutofillHints@postalAddress': (m.Scope scope)=>AutofillHints.postalAddress,
'package:flutter/src/services/autofill.dart@AutofillHints@postalAddressExtended': (m.Scope scope)=>AutofillHints.postalAddressExtended,
'package:flutter/src/services/autofill.dart@AutofillHints@postalAddressExtendedPostalCode': (m.Scope scope)=>AutofillHints.postalAddressExtendedPostalCode,
'package:flutter/src/services/autofill.dart@AutofillHints@postalCode': (m.Scope scope)=>AutofillHints.postalCode,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLevel1': (m.Scope scope)=>AutofillHints.streetAddressLevel1,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLevel2': (m.Scope scope)=>AutofillHints.streetAddressLevel2,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLevel3': (m.Scope scope)=>AutofillHints.streetAddressLevel3,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLevel4': (m.Scope scope)=>AutofillHints.streetAddressLevel4,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLine1': (m.Scope scope)=>AutofillHints.streetAddressLine1,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLine2': (m.Scope scope)=>AutofillHints.streetAddressLine2,
'package:flutter/src/services/autofill.dart@AutofillHints@streetAddressLine3': (m.Scope scope)=>AutofillHints.streetAddressLine3,
'package:flutter/src/services/autofill.dart@AutofillHints@sublocality': (m.Scope scope)=>AutofillHints.sublocality,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumber': (m.Scope scope)=>AutofillHints.telephoneNumber,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberAreaCode': (m.Scope scope)=>AutofillHints.telephoneNumberAreaCode,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberCountryCode': (m.Scope scope)=>AutofillHints.telephoneNumberCountryCode,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberDevice': (m.Scope scope)=>AutofillHints.telephoneNumberDevice,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberExtension': (m.Scope scope)=>AutofillHints.telephoneNumberExtension,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberLocal': (m.Scope scope)=>AutofillHints.telephoneNumberLocal,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberLocalPrefix': (m.Scope scope)=>AutofillHints.telephoneNumberLocalPrefix,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberLocalSuffix': (m.Scope scope)=>AutofillHints.telephoneNumberLocalSuffix,
'package:flutter/src/services/autofill.dart@AutofillHints@telephoneNumberNational': (m.Scope scope)=>AutofillHints.telephoneNumberNational,
'package:flutter/src/services/autofill.dart@AutofillHints@transactionAmount': (m.Scope scope)=>AutofillHints.transactionAmount,
'package:flutter/src/services/autofill.dart@AutofillHints@transactionCurrency': (m.Scope scope)=>AutofillHints.transactionCurrency,
'package:flutter/src/services/autofill.dart@AutofillHints@url': (m.Scope scope)=>AutofillHints.url,
'package:flutter/src/services/autofill.dart@AutofillHints@username': (m.Scope scope)=>AutofillHints.username,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@#as': (m.Scope scope, target)=>()=>target as AutofillConfiguration,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@#is': (m.Scope scope, target)=>()=>target is AutofillConfiguration,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@disabled': (m.Scope scope)=>AutofillConfiguration.disabled,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@enabled': (m.Scope scope, AutofillConfiguration target)=>target.enabled,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@uniqueIdentifier': (m.Scope scope, AutofillConfiguration target)=>target.uniqueIdentifier,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@autofillHints': (m.Scope scope, AutofillConfiguration target)=>target.autofillHints,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@currentEditingValue': (m.Scope scope, AutofillConfiguration target)=>target.currentEditingValue,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@hintText': (m.Scope scope, AutofillConfiguration target)=>target.hintText,
'package:flutter/src/services/autofill.dart@AutofillConfiguration@': (m.Scope scope)=>({ autofillHints,  currentEditingValue,  hintText,  uniqueIdentifier}){
return AutofillConfiguration(autofillHints:autofillHints, currentEditingValue:currentEditingValue, hintText:hintText, uniqueIdentifier:uniqueIdentifier);
},
'package:flutter/src/services/autofill.dart@AutofillConfiguration@toJson': (m.Scope scope, AutofillConfiguration target)=>target.toJson,
'package:flutter/src/services/autofill.dart@AutofillClient@#as': (m.Scope scope, target)=>()=>target as AutofillClient,
'package:flutter/src/services/autofill.dart@AutofillClient@#is': (m.Scope scope, target)=>()=>target is AutofillClient,
'package:flutter/src/services/autofill.dart@AutofillClient@autofillId': (m.Scope scope, AutofillClient target)=>target.autofillId,
'package:flutter/src/services/autofill.dart@AutofillClient@textInputConfiguration': (m.Scope scope, AutofillClient target)=>target.textInputConfiguration,
'package:flutter/src/services/autofill.dart@AutofillClient@autofill': (m.Scope scope, AutofillClient target)=>target.autofill,
'package:flutter/src/services/autofill.dart@AutofillScope@#as': (m.Scope scope, target)=>()=>target as AutofillScope,
'package:flutter/src/services/autofill.dart@AutofillScope@#is': (m.Scope scope, target)=>()=>target is AutofillScope,
'package:flutter/src/services/autofill.dart@AutofillScope@autofillClients': (m.Scope scope, AutofillScope target)=>target.autofillClients,
'package:flutter/src/services/autofill.dart@AutofillScope@getAutofillClient': (m.Scope scope, AutofillScope target)=>target.getAutofillClient,
'package:flutter/src/services/autofill.dart@AutofillScope@attach': (m.Scope scope, AutofillScope target)=>target.attach,

};
}