import 'package:flutter/src/rendering/debug.dart';
import 'package:flutter/src/rendering/box.dart';
import 'package:flutter/src/rendering/object.dart';
import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
Map<String,Function> getLibrary(m.MicroDartEngine engine) {
return {
'package:flutter/src/rendering/debug.dart@@debugPaintSizeEnabled': (m.Scope scope)=>debugPaintSizeEnabled,
'package:flutter/src/rendering/debug.dart@@debugPaintSizeEnabled:set': (m.Scope scope)=>(other)=>debugPaintSizeEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugPaintBaselinesEnabled': (m.Scope scope)=>debugPaintBaselinesEnabled,
'package:flutter/src/rendering/debug.dart@@debugPaintBaselinesEnabled:set': (m.Scope scope)=>(other)=>debugPaintBaselinesEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugPaintLayerBordersEnabled': (m.Scope scope)=>debugPaintLayerBordersEnabled,
'package:flutter/src/rendering/debug.dart@@debugPaintLayerBordersEnabled:set': (m.Scope scope)=>(other)=>debugPaintLayerBordersEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugPaintPointersEnabled': (m.Scope scope)=>debugPaintPointersEnabled,
'package:flutter/src/rendering/debug.dart@@debugPaintPointersEnabled:set': (m.Scope scope)=>(other)=>debugPaintPointersEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugRepaintRainbowEnabled': (m.Scope scope)=>debugRepaintRainbowEnabled,
'package:flutter/src/rendering/debug.dart@@debugRepaintRainbowEnabled:set': (m.Scope scope)=>(other)=>debugRepaintRainbowEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugRepaintTextRainbowEnabled': (m.Scope scope)=>debugRepaintTextRainbowEnabled,
'package:flutter/src/rendering/debug.dart@@debugRepaintTextRainbowEnabled:set': (m.Scope scope)=>(other)=>debugRepaintTextRainbowEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugCurrentRepaintColor': (m.Scope scope)=>debugCurrentRepaintColor,
'package:flutter/src/rendering/debug.dart@@debugCurrentRepaintColor:set': (m.Scope scope)=>(other)=>debugCurrentRepaintColor=other,
'package:flutter/src/rendering/debug.dart@@debugPrintMarkNeedsLayoutStacks': (m.Scope scope)=>debugPrintMarkNeedsLayoutStacks,
'package:flutter/src/rendering/debug.dart@@debugPrintMarkNeedsLayoutStacks:set': (m.Scope scope)=>(other)=>debugPrintMarkNeedsLayoutStacks=other,
'package:flutter/src/rendering/debug.dart@@debugPrintMarkNeedsPaintStacks': (m.Scope scope)=>debugPrintMarkNeedsPaintStacks,
'package:flutter/src/rendering/debug.dart@@debugPrintMarkNeedsPaintStacks:set': (m.Scope scope)=>(other)=>debugPrintMarkNeedsPaintStacks=other,
'package:flutter/src/rendering/debug.dart@@debugPrintLayouts': (m.Scope scope)=>debugPrintLayouts,
'package:flutter/src/rendering/debug.dart@@debugPrintLayouts:set': (m.Scope scope)=>(other)=>debugPrintLayouts=other,
'package:flutter/src/rendering/debug.dart@@debugCheckIntrinsicSizes': (m.Scope scope)=>debugCheckIntrinsicSizes,
'package:flutter/src/rendering/debug.dart@@debugCheckIntrinsicSizes:set': (m.Scope scope)=>(other)=>debugCheckIntrinsicSizes=other,
'package:flutter/src/rendering/debug.dart@@debugProfileLayoutsEnabled': (m.Scope scope)=>debugProfileLayoutsEnabled,
'package:flutter/src/rendering/debug.dart@@debugProfileLayoutsEnabled:set': (m.Scope scope)=>(other)=>debugProfileLayoutsEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugProfilePaintsEnabled': (m.Scope scope)=>debugProfilePaintsEnabled,
'package:flutter/src/rendering/debug.dart@@debugProfilePaintsEnabled:set': (m.Scope scope)=>(other)=>debugProfilePaintsEnabled=other,
'package:flutter/src/rendering/debug.dart@@debugEnhanceLayoutTimelineArguments': (m.Scope scope)=>debugEnhanceLayoutTimelineArguments,
'package:flutter/src/rendering/debug.dart@@debugEnhanceLayoutTimelineArguments:set': (m.Scope scope)=>(other)=>debugEnhanceLayoutTimelineArguments=other,
'package:flutter/src/rendering/debug.dart@@debugEnhancePaintTimelineArguments': (m.Scope scope)=>debugEnhancePaintTimelineArguments,
'package:flutter/src/rendering/debug.dart@@debugEnhancePaintTimelineArguments:set': (m.Scope scope)=>(other)=>debugEnhancePaintTimelineArguments=other,
'package:flutter/src/rendering/debug.dart@@debugOnProfilePaint': (m.Scope scope)=>debugOnProfilePaint,
'package:flutter/src/rendering/debug.dart@@debugOnProfilePaint:set': (m.Scope scope)=>(other)=>debugOnProfilePaint=other,
'package:flutter/src/rendering/debug.dart@@debugDisableClipLayers': (m.Scope scope)=>debugDisableClipLayers,
'package:flutter/src/rendering/debug.dart@@debugDisableClipLayers:set': (m.Scope scope)=>(other)=>debugDisableClipLayers=other,
'package:flutter/src/rendering/debug.dart@@debugDisablePhysicalShapeLayers': (m.Scope scope)=>debugDisablePhysicalShapeLayers,
'package:flutter/src/rendering/debug.dart@@debugDisablePhysicalShapeLayers:set': (m.Scope scope)=>(other)=>debugDisablePhysicalShapeLayers=other,
'package:flutter/src/rendering/debug.dart@@debugDisableOpacityLayers': (m.Scope scope)=>debugDisableOpacityLayers,
'package:flutter/src/rendering/debug.dart@@debugDisableOpacityLayers:set': (m.Scope scope)=>(other)=>debugDisableOpacityLayers=other,
'package:flutter/src/rendering/debug.dart@@debugPaintPadding': (m.Scope scope)=>debugPaintPadding,
'package:flutter/src/rendering/debug.dart@@debugAssertAllRenderVarsUnset': (m.Scope scope)=>debugAssertAllRenderVarsUnset,
'package:flutter/src/rendering/debug.dart@@debugCheckHasBoundedAxis': (m.Scope scope)=>debugCheckHasBoundedAxis,

};
}