// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:clock/clock.dart';
import 'package:clock/src/default.dart';

const libraryMirror = m.LibraryMirror(
  'package:clock/clock.dart',
  {},
  {},
  {},
);
