// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:intl/src/intl/micro_money.dart';

const libraryMirror = m.LibraryMirror(
  'package:intl/src/intl/micro_money.dart',
  {'MicroMoney.': _MicroMoney__$},
  {},
  {
    'MicroMoney': m.ClassMirror(
      'MicroMoney',
      {
        '#as': MicroMoney_as$,
        '#is': MicroMoney_is$,
      },
      {},
    )
  },
);
Function MicroMoney_as$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ as MicroMoney;
Function MicroMoney_is$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ is MicroMoney;
Function _MicroMoney__$(m.Scope scope$) => (dynamic micros) {
      return MicroMoney(micros);
    };
