// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:flutter_localizations/src/utils/date_localizations.dart';
import 'package:intl/date_symbol_data_custom.dart';
import 'package:intl/date_symbols.dart';
import 'package:flutter_localizations/src/l10n/generated_date_localizations.dart';

const libraryMirror = m.LibraryMirror(
  'package:flutter_localizations/src/utils/date_localizations.dart',
  {'loadDateIntlDataIfNotLoaded': _loadDateIntlDataIfNotLoaded$},
  {},
  {},
);
Function _loadDateIntlDataIfNotLoaded$(m.Scope scope$) =>
    loadDateIntlDataIfNotLoaded;
