// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:material_color_utilities/quantize/point_provider.dart';

const libraryMirror = m.LibraryMirror(
  'package:material_color_utilities/quantize/point_provider.dart',
  {},
  {},
  {
    'PointProvider': m.ClassMirror(
      'PointProvider',
      {
        '#as': PointProvider_as$,
        '#is': PointProvider_is$,
        'fromInt': _PointProvider_fromInt$,
        'toInt': _PointProvider_toInt$,
        'distance': _PointProvider_distance$,
      },
      {},
    )
  },
);
Function PointProvider_as$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ as PointProvider;
Function PointProvider_is$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ is PointProvider;
Function _PointProvider_fromInt$(
  m.Scope scope$,
  PointProvider target$,
) =>
    target$.fromInt;
Function _PointProvider_toInt$(
  m.Scope scope$,
  PointProvider target$,
) =>
    target$.toInt;
Function _PointProvider_distance$(
  m.Scope scope$,
  PointProvider target$,
) =>
    target$.distance;
