// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:url_launcher/src/url_launcher_string.dart';
import 'package:url_launcher_platform_interface/url_launcher_platform_interface.dart';
import 'package:url_launcher/src/type_conversion.dart';
import 'package:url_launcher/src/types.dart';

const libraryMirror = m.LibraryMirror(
  'package:url_launcher/src/url_launcher_string.dart',
  {
    'launchUrlString': _launchUrlString$,
    'canLaunchUrlString': _canLaunchUrlString$,
  },
  {},
  {},
);
Function _launchUrlString$(m.Scope scope$) => launchUrlString;
Function _canLaunchUrlString$(m.Scope scope$) => canLaunchUrlString;
