// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:clock/src/default.dart';
import 'dart:async';
import 'package:clock/src/clock.dart';

const libraryMirror = m.LibraryMirror(
  'package:clock/src/default.dart',
  {
    'clock': _clock$,
    'withClock': _withClock$,
  },
  {},
  {},
);
Function _clock$(m.Scope scope$) => () => clock;
Function _withClock$(m.Scope scope$) => (
      Clock clock,
      m.FunctionPointer callback, {
      bool? isFinal,
    }) {
      dynamic callbackProxy() => scope$.engine.callFunctionPointer(
            scope$,
            callback,
            [],
            {},
          );
      return withClock(
        clock,
        callbackProxy,
        isFinal: isFinal ?? false,
      );
    };
