// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';

const libraryMirror = m.LibraryMirror(
  'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart',
  {},
  {},
  {},
);
