// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:url_launcher_platform_interface/url_launcher_platform_interface.dart';

const libraryMirror = m.LibraryMirror(
  'package:url_launcher_platform_interface/url_launcher_platform_interface.dart',
  {},
  {},
  {},
);
