// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:collection/src/iterable_extensions.dart';
import 'dart:math' show Random;
import 'package:collection/src/algorithms.dart';
import 'package:collection/src/functions.dart';
import 'package:collection/src/utils.dart';

const libraryMirror = m.LibraryMirror(
  'package:collection/src/iterable_extensions.dart',
  {},
  {},
  {},
);
