// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:intl/src/intl/date_computation.dart';

const libraryMirror = m.LibraryMirror(
  'package:intl/src/intl/date_computation.dart',
  {
    'dayOfYear': _dayOfYear$,
    'isLeapYear': _isLeapYear$,
    'ordinalDayFromMarchFirst': _ordinalDayFromMarchFirst$,
  },
  {},
  {},
);
Function _dayOfYear$(m.Scope scope$) => dayOfYear;
Function _isLeapYear$(m.Scope scope$) => isLeapYear;
Function _ordinalDayFromMarchFirst$(m.Scope scope$) => ordinalDayFromMarchFirst;
