// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:characters/src/grapheme_clusters/table.dart';

const libraryMirror = m.LibraryMirror(
  'package:characters/src/grapheme_clusters/table.dart',
  {
    'low': _low$,
    'high': _high$,
    'move': _move$,
    'moveBack': _moveBack$,
  },
  {},
  {},
);
Function _low$(m.Scope scope$) => low;
Function _high$(m.Scope scope$) => high;
Function _move$(m.Scope scope$) => move;
Function _moveBack$(m.Scope scope$) => moveBack;
