// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:flutter_localizations/src/widgets_localizations.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/src/l10n/generated_widgets_localizations.dart';

const libraryMirror = m.LibraryMirror(
  'package:flutter_localizations/src/widgets_localizations.dart',
  {
    'GlobalWidgetsLocalizations.delegate': _GlobalWidgetsLocalizations_delegate$
  },
  {},
  {
    'GlobalWidgetsLocalizations': m.ClassMirror(
      'GlobalWidgetsLocalizations',
      {
        '#as': GlobalWidgetsLocalizations_as$,
        '#is': GlobalWidgetsLocalizations_is$,
        'textDirection': _GlobalWidgetsLocalizations_textDirection$,
      },
      {},
    )
  },
);
Function GlobalWidgetsLocalizations_as$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ as GlobalWidgetsLocalizations;
Function GlobalWidgetsLocalizations_is$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ is GlobalWidgetsLocalizations;
Function _GlobalWidgetsLocalizations_textDirection$(
  m.Scope scope$,
  GlobalWidgetsLocalizations target$,
) =>
    () {
      return target$.textDirection;
    };
Function _GlobalWidgetsLocalizations_delegate$(m.Scope scope$) =>
    () => GlobalWidgetsLocalizations.delegate;
