// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:intl/src/intl/constants.dart';

const libraryMirror = m.LibraryMirror(
  'package:intl/src/intl/constants.dart',
  {
    'asciiZeroCodeUnit': _asciiZeroCodeUnit$,
    'simpleCurrencySymbols': _simpleCurrencySymbols$,
  },
  {},
  {},
);
Function _asciiZeroCodeUnit$(m.Scope scope$) => () => asciiZeroCodeUnit;
Function _simpleCurrencySymbols$(m.Scope scope$) => () => simpleCurrencySymbols;
