// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:flutter_staggered_grid_view/src/widgets/aligned_grid_view.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/src/rendering/sliver_simple_grid_delegate.dart';
import 'package:flutter_staggered_grid_view/src/widgets/sliver_aligned_grid.dart';

const libraryMirror = m.LibraryMirror(
  'package:flutter_staggered_grid_view/src/widgets/aligned_grid_view.dart',
  {
    'AlignedGridView.custom': _AlignedGridView_custom_$,
    'AlignedGridView.count': _AlignedGridView_count_$,
    'AlignedGridView.extent': _AlignedGridView_extent_$,
  },
  {},
  {
    'AlignedGridView': m.ClassMirror(
      'AlignedGridView',
      {
        '#as': AlignedGridView_as$,
        '#is': AlignedGridView_is$,
        'gridDelegate': _AlignedGridView_gridDelegate$,
        'mainAxisSpacing': _AlignedGridView_mainAxisSpacing$,
        'crossAxisSpacing': _AlignedGridView_crossAxisSpacing$,
        'itemBuilder': _AlignedGridView_itemBuilder$,
        'itemCount': _AlignedGridView_itemCount$,
        'addAutomaticKeepAlives': _AlignedGridView_addAutomaticKeepAlives$,
        'addRepaintBoundaries': _AlignedGridView_addRepaintBoundaries$,
        'buildChildLayout': _AlignedGridView_buildChildLayout$,
      },
      {},
    )
  },
);
Function AlignedGridView_as$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ as AlignedGridView;
Function AlignedGridView_is$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ is AlignedGridView;
Function _AlignedGridView_gridDelegate$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.gridDelegate;
    };
Function _AlignedGridView_mainAxisSpacing$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.mainAxisSpacing;
    };
Function _AlignedGridView_crossAxisSpacing$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.crossAxisSpacing;
    };
Function _AlignedGridView_itemBuilder$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.itemBuilder;
    };
Function _AlignedGridView_itemCount$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.itemCount;
    };
Function _AlignedGridView_addAutomaticKeepAlives$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.addAutomaticKeepAlives;
    };
Function _AlignedGridView_addRepaintBoundaries$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    () {
      return target$.addRepaintBoundaries;
    };
Function _AlignedGridView_custom_$(m.Scope scope$) => ({
      Key? key,
      Axis? scrollDirection,
      bool? reverse,
      ScrollController? controller,
      bool? primary,
      ScrollPhysics? physics,
      bool? shrinkWrap,
      EdgeInsetsGeometry? padding,
      required SliverSimpleGridDelegate gridDelegate,
      required m.FunctionPointer itemBuilder,
      int? itemCount,
      bool? addAutomaticKeepAlives,
      bool? addRepaintBoundaries,
      double? mainAxisSpacing,
      double? crossAxisSpacing,
      double? cacheExtent,
      int? semanticChildCount,
      DragStartBehavior? dragStartBehavior,
      ScrollViewKeyboardDismissBehavior? keyboardDismissBehavior,
      String? restorationId,
      Clip? clipBehavior,
    }) {
      Widget? itemBuilderProxy(
        BuildContext itemBuilder_context$,
        int itemBuilder_index$,
      ) =>
          scope$.engine.callFunctionPointer(
            scope$,
            itemBuilder,
            [
              itemBuilder_context$,
              itemBuilder_index$,
            ],
            {},
          );
      return AlignedGridView.custom(
        addAutomaticKeepAlives: addAutomaticKeepAlives ?? true,
        addRepaintBoundaries: addRepaintBoundaries ?? true,
        cacheExtent: cacheExtent,
        clipBehavior: clipBehavior ?? Clip.hardEdge,
        controller: controller,
        crossAxisSpacing: crossAxisSpacing ?? 0.0,
        dragStartBehavior: dragStartBehavior ?? DragStartBehavior.start,
        gridDelegate: gridDelegate,
        itemBuilder: itemBuilderProxy,
        itemCount: itemCount,
        key: key,
        keyboardDismissBehavior:
            keyboardDismissBehavior ?? ScrollViewKeyboardDismissBehavior.manual,
        mainAxisSpacing: mainAxisSpacing ?? 0.0,
        padding: padding,
        physics: physics,
        primary: primary,
        restorationId: restorationId,
        reverse: reverse ?? false,
        scrollDirection: scrollDirection ?? Axis.vertical,
        semanticChildCount: semanticChildCount,
        shrinkWrap: shrinkWrap ?? false,
      );
    };
Function _AlignedGridView_count_$(m.Scope scope$) => ({
      Key? key,
      Axis? scrollDirection,
      bool? reverse,
      ScrollController? controller,
      bool? primary,
      ScrollPhysics? physics,
      bool? shrinkWrap,
      EdgeInsetsGeometry? padding,
      required int crossAxisCount,
      double? mainAxisSpacing,
      double? crossAxisSpacing,
      required m.FunctionPointer itemBuilder,
      int? itemCount,
      bool? addAutomaticKeepAlives,
      bool? addRepaintBoundaries,
      double? cacheExtent,
      int? semanticChildCount,
      DragStartBehavior? dragStartBehavior,
      ScrollViewKeyboardDismissBehavior? keyboardDismissBehavior,
      String? restorationId,
      Clip? clipBehavior,
    }) {
      Widget? itemBuilderProxy(
        BuildContext itemBuilder_context$,
        int itemBuilder_index$,
      ) =>
          scope$.engine.callFunctionPointer(
            scope$,
            itemBuilder,
            [
              itemBuilder_context$,
              itemBuilder_index$,
            ],
            {},
          );
      return AlignedGridView.count(
        addAutomaticKeepAlives: addAutomaticKeepAlives ?? true,
        addRepaintBoundaries: addRepaintBoundaries ?? true,
        cacheExtent: cacheExtent,
        clipBehavior: clipBehavior ?? Clip.hardEdge,
        controller: controller,
        crossAxisCount: crossAxisCount,
        crossAxisSpacing: crossAxisSpacing ?? 0.0,
        dragStartBehavior: dragStartBehavior ?? DragStartBehavior.start,
        itemBuilder: itemBuilderProxy,
        itemCount: itemCount,
        key: key,
        keyboardDismissBehavior:
            keyboardDismissBehavior ?? ScrollViewKeyboardDismissBehavior.manual,
        mainAxisSpacing: mainAxisSpacing ?? 0.0,
        padding: padding,
        physics: physics,
        primary: primary,
        restorationId: restorationId,
        reverse: reverse ?? false,
        scrollDirection: scrollDirection ?? Axis.vertical,
        semanticChildCount: semanticChildCount,
        shrinkWrap: shrinkWrap ?? false,
      );
    };
Function _AlignedGridView_extent_$(m.Scope scope$) => ({
      Key? key,
      Axis? scrollDirection,
      bool? reverse,
      ScrollController? controller,
      bool? primary,
      ScrollPhysics? physics,
      bool? shrinkWrap,
      EdgeInsetsGeometry? padding,
      required double maxCrossAxisExtent,
      double? mainAxisSpacing,
      double? crossAxisSpacing,
      required m.FunctionPointer itemBuilder,
      int? itemCount,
      bool? addAutomaticKeepAlives,
      bool? addRepaintBoundaries,
      double? cacheExtent,
      int? semanticChildCount,
      DragStartBehavior? dragStartBehavior,
      ScrollViewKeyboardDismissBehavior? keyboardDismissBehavior,
      String? restorationId,
      Clip? clipBehavior,
    }) {
      Widget? itemBuilderProxy(
        BuildContext itemBuilder_context$,
        int itemBuilder_index$,
      ) =>
          scope$.engine.callFunctionPointer(
            scope$,
            itemBuilder,
            [
              itemBuilder_context$,
              itemBuilder_index$,
            ],
            {},
          );
      return AlignedGridView.extent(
        addAutomaticKeepAlives: addAutomaticKeepAlives ?? true,
        addRepaintBoundaries: addRepaintBoundaries ?? true,
        cacheExtent: cacheExtent,
        clipBehavior: clipBehavior ?? Clip.hardEdge,
        controller: controller,
        crossAxisSpacing: crossAxisSpacing ?? 0.0,
        dragStartBehavior: dragStartBehavior ?? DragStartBehavior.start,
        itemBuilder: itemBuilderProxy,
        itemCount: itemCount,
        key: key,
        keyboardDismissBehavior:
            keyboardDismissBehavior ?? ScrollViewKeyboardDismissBehavior.manual,
        mainAxisSpacing: mainAxisSpacing ?? 0.0,
        maxCrossAxisExtent: maxCrossAxisExtent,
        padding: padding,
        physics: physics,
        primary: primary,
        restorationId: restorationId,
        reverse: reverse ?? false,
        scrollDirection: scrollDirection ?? Axis.vertical,
        semanticChildCount: semanticChildCount,
        shrinkWrap: shrinkWrap ?? false,
      );
    };
Function _AlignedGridView_buildChildLayout$(
  m.Scope scope$,
  AlignedGridView target$,
) =>
    target$.buildChildLayout;
