// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:flutter_staggered_grid_view/src/foundation/constants.dart';
import 'package:flutter/rendering.dart';

const libraryMirror = m.LibraryMirror(
  'package:flutter_staggered_grid_view/src/foundation/constants.dart',
  {'kZeroGeometry': _kZeroGeometry$},
  {},
  {},
);
Function _kZeroGeometry$(m.Scope scope$) => () => kZeroGeometry;
