// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:characters/src/extensions.dart';
import 'package:characters/src/characters.dart';

const libraryMirror = m.LibraryMirror(
  'package:characters/src/extensions.dart',
  {},
  {},
  {},
);
