// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:intl/src/global_state.dart';
import 'dart:async';

const libraryMirror = m.LibraryMirror(
  'package:intl/src/global_state.dart',
  {
    'systemLocale': _systemLocale$,
    'defaultLocale': _defaultLocale$,
    'getCurrentLocale': _getCurrentLocale$,
  },
  {
    'systemLocale': _systemLocale_set$,
    'defaultLocale': _defaultLocale_set$,
  },
  {},
);
Function _systemLocale$(m.Scope scope$) => () => systemLocale;
void _systemLocale_set$(String other$) {
  systemLocale = other$;
}

void _defaultLocale_set$(String? other$) {
  defaultLocale = other$;
}

Function _defaultLocale$(m.Scope scope$) => () => defaultLocale;
Function _getCurrentLocale$(m.Scope scope$) => getCurrentLocale;
