// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:provider/src/reassemble_handler.dart';
import 'package:flutter/foundation.dart' show BindingBase;
import 'package:flutter/widgets.dart' show Element;

const libraryMirror = m.LibraryMirror(
  'package:provider/src/reassemble_handler.dart',
  {},
  {},
  {
    'ReassembleHandler': m.ClassMirror(
      'ReassembleHandler',
      {
        '#as': ReassembleHandler_as$,
        '#is': ReassembleHandler_is$,
        'reassemble': _ReassembleHandler_reassemble$,
      },
      {},
    )
  },
);
Function ReassembleHandler_as$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ as ReassembleHandler;
Function ReassembleHandler_is$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ is ReassembleHandler;
Function _ReassembleHandler_reassemble$(
  m.Scope scope$,
  ReassembleHandler target$,
) =>
    target$.reassemble;
