// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:material_color_utilities/utils/color_utils.dart';
import 'dart:math';
import 'package:material_color_utilities/utils/math_utils.dart';

const libraryMirror = m.LibraryMirror(
  'package:material_color_utilities/utils/color_utils.dart',
  {
    'ColorUtils.': _ColorUtils__$,
    'ColorUtils.argbFromRgb': _ColorUtils_argbFromRgb$,
    'ColorUtils.argbFromLinrgb': _ColorUtils_argbFromLinrgb$,
    'ColorUtils.alphaFromArgb': _ColorUtils_alphaFromArgb$,
    'ColorUtils.redFromArgb': _ColorUtils_redFromArgb$,
    'ColorUtils.greenFromArgb': _ColorUtils_greenFromArgb$,
    'ColorUtils.blueFromArgb': _ColorUtils_blueFromArgb$,
    'ColorUtils.isOpaque': _ColorUtils_isOpaque$,
    'ColorUtils.argbFromXyz': _ColorUtils_argbFromXyz$,
    'ColorUtils.xyzFromArgb': _ColorUtils_xyzFromArgb$,
    'ColorUtils.argbFromLab': _ColorUtils_argbFromLab$,
    'ColorUtils.labFromArgb': _ColorUtils_labFromArgb$,
    'ColorUtils.argbFromLstar': _ColorUtils_argbFromLstar$,
    'ColorUtils.lstarFromArgb': _ColorUtils_lstarFromArgb$,
    'ColorUtils.yFromLstar': _ColorUtils_yFromLstar$,
    'ColorUtils.linearized': _ColorUtils_linearized$,
    'ColorUtils.delinearized': _ColorUtils_delinearized$,
    'ColorUtils.whitePointD65': _ColorUtils_whitePointD65$,
  },
  {},
  {
    'ColorUtils': m.ClassMirror(
      'ColorUtils',
      {
        '#as': ColorUtils_as$,
        '#is': ColorUtils_is$,
      },
      {},
    )
  },
);
Function ColorUtils_as$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ as ColorUtils;
Function ColorUtils_is$(
  m.Scope scope$,
  dynamic target$,
) =>
    () => target$ is ColorUtils;
Function _ColorUtils__$(m.Scope scope$) => () {
      return ColorUtils();
    };
Function _ColorUtils_argbFromRgb$(m.Scope scope$) => ColorUtils.argbFromRgb;
Function _ColorUtils_argbFromLinrgb$(m.Scope scope$) =>
    ColorUtils.argbFromLinrgb;
Function _ColorUtils_alphaFromArgb$(m.Scope scope$) => ColorUtils.alphaFromArgb;
Function _ColorUtils_redFromArgb$(m.Scope scope$) => ColorUtils.redFromArgb;
Function _ColorUtils_greenFromArgb$(m.Scope scope$) => ColorUtils.greenFromArgb;
Function _ColorUtils_blueFromArgb$(m.Scope scope$) => ColorUtils.blueFromArgb;
Function _ColorUtils_isOpaque$(m.Scope scope$) => ColorUtils.isOpaque;
Function _ColorUtils_argbFromXyz$(m.Scope scope$) => ColorUtils.argbFromXyz;
Function _ColorUtils_xyzFromArgb$(m.Scope scope$) => ColorUtils.xyzFromArgb;
Function _ColorUtils_argbFromLab$(m.Scope scope$) => ColorUtils.argbFromLab;
Function _ColorUtils_labFromArgb$(m.Scope scope$) => ColorUtils.labFromArgb;
Function _ColorUtils_argbFromLstar$(m.Scope scope$) => ColorUtils.argbFromLstar;
Function _ColorUtils_lstarFromArgb$(m.Scope scope$) => ColorUtils.lstarFromArgb;
Function _ColorUtils_yFromLstar$(m.Scope scope$) => ColorUtils.yFromLstar;
Function _ColorUtils_linearized$(m.Scope scope$) => ColorUtils.linearized;
Function _ColorUtils_delinearized$(m.Scope scope$) => ColorUtils.delinearized;
Function _ColorUtils_whitePointD65$(m.Scope scope$) => ColorUtils.whitePointD65;
