// generated by micro_dart_generator
// ignore_for_file: non_constant_identifier_names

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import 'package:flutter_example_gallery/constants.dart';
import 'dart:typed_data';

const libraryMirror = m.LibraryMirror(
  'package:flutter_example_gallery/constants.dart',
  {
    'galleryHeaderHeight': _galleryHeaderHeight$,
    'desktopDisplay1FontDelta': _desktopDisplay1FontDelta$,
    'desktopSettingsWidth': _desktopSettingsWidth$,
    'systemTextScaleFactorOption': _systemTextScaleFactorOption$,
    'splashPageAnimationDuration': _splashPageAnimationDuration$,
    'halfSplashPageAnimationDuration': _halfSplashPageAnimationDuration$,
    'settingsPanelMobileAnimationDuration':
        _settingsPanelMobileAnimationDuration$,
    'settingsPanelDesktopAnimationDuration':
        _settingsPanelDesktopAnimationDuration$,
    'entranceAnimationDuration': _entranceAnimationDuration$,
    'firstHeaderDesktopTopPadding': _firstHeaderDesktopTopPadding$,
    'kTransparentImage': _kTransparentImage$,
  },
  {},
  {},
);
Function _galleryHeaderHeight$(m.Scope scope$) => () => galleryHeaderHeight;
Function _desktopDisplay1FontDelta$(m.Scope scope$) =>
    () => desktopDisplay1FontDelta;
Function _desktopSettingsWidth$(m.Scope scope$) => () => desktopSettingsWidth;
Function _systemTextScaleFactorOption$(m.Scope scope$) =>
    () => systemTextScaleFactorOption;
Function _splashPageAnimationDuration$(m.Scope scope$) =>
    () => splashPageAnimationDuration;
Function _halfSplashPageAnimationDuration$(m.Scope scope$) =>
    () => halfSplashPageAnimationDuration;
Function _settingsPanelMobileAnimationDuration$(m.Scope scope$) =>
    () => settingsPanelMobileAnimationDuration;
Function _settingsPanelDesktopAnimationDuration$(m.Scope scope$) =>
    () => settingsPanelDesktopAnimationDuration;
Function _entranceAnimationDuration$(m.Scope scope$) =>
    () => entranceAnimationDuration;
Function _firstHeaderDesktopTopPadding$(m.Scope scope$) =>
    () => firstHeaderDesktopTopPadding;
Function _kTransparentImage$(m.Scope scope$) => () => kTransparentImage;
