// generated by micro_dart_generator

import 'package:micro_dart_runtime/micro_dart_runtime.dart' as m;
import '__package_flutter_example_gallery_main.dart' as l1;
import '__package_flutter_example_gallery_all.dart' as l2;
import '__package_flutter_example_gallery_gen_l10n_gallery_localizations.dart'
    as l3;
import '__package_flutter_example_gallery_data_gallery_options.dart' as l4;
import '__package_flutter_example_gallery_pages_splash.dart' as l5;
import '__package_flutter_example_gallery_constants.dart' as l6;
import '__package_flutter_example_gallery_sdudies_shirine_page_status.dart'
    as l7;
import '__package_flutter_example_gallery_sdudies_shirine_supplemental_layout_cache.dart'
    as l8;
import '__package_flutter_example_gallery_layout_adaptive.dart' as l9;
import '__package_flutter_example_gallery_codeviewer_code_style.dart' as l10;
import '__package_scoped_model_scoped_model.dart' as l11;
import '__package_url_launcher_url_launcher.dart' as l12;
import '__package_animations_animations.dart' as l13;
import '__package_flutter_staggered_grid_view_flutter_staggered_grid_view.dart'
    as l14;
import '__package_path_provider_path_provider.dart' as l15;
import '__package_provider_provider.dart' as l16;
import '__package_vector_math_vector_math_64.dart' as l17;
import '__package_material_color_utilities_material_color_utilities.dart'
    as l18;
import '__package_characters_characters.dart' as l19;
import '__package_meta_meta.dart' as l20;
import '__package_flutter_localizations_flutter_localizations.dart' as l21;
import '__package_intl_intl.dart' as l22;
import '__package_flutter_example_gallery_gen_l10n_gallery_localizations_en.dart'
    as l23;
import '__package_flutter_example_gallery_gen_l10n_gallery_localizations_zh.dart'
    as l24;
import '__package_dual_screen_dual_screen.dart' as l25;
import '__package_url_launcher_src_legacy_api.dart' as l26;
import '__package_url_launcher_src_types.dart' as l27;
import '__package_url_launcher_src_url_launcher_uri.dart' as l28;
import '__package_animations_src_fade_scale_transition.dart' as l29;
import '__package_animations_src_fade_through_transition.dart' as l30;
import '__package_animations_src_modal.dart' as l31;
import '__package_animations_src_open_container.dart' as l32;
import '__package_animations_src_page_transition_switcher.dart' as l33;
import '__package_animations_src_shared_axis_transition.dart' as l34;
import '__package_flutter_staggered_grid_view_src_layouts_quilted.dart' as l35;
import '__package_flutter_staggered_grid_view_src_layouts_staired.dart' as l36;
import '__package_flutter_staggered_grid_view_src_layouts_woven.dart' as l37;
import '__package_flutter_staggered_grid_view_src_rendering_sliver_masonry_grid.dart'
    as l38;
import '__package_flutter_staggered_grid_view_src_rendering_sliver_simple_grid_delegate.dart'
    as l39;
import '__package_flutter_staggered_grid_view_src_widgets_aligned_grid_view.dart'
    as l40;
import '__package_flutter_staggered_grid_view_src_widgets_masonry_grid_view.dart'
    as l41;
import '__package_flutter_staggered_grid_view_src_widgets_sliver_aligned_grid.dart'
    as l42;
import '__package_flutter_staggered_grid_view_src_widgets_sliver_masonry_grid.dart'
    as l43;
import '__package_flutter_staggered_grid_view_src_widgets_staggered_grid.dart'
    as l44;
import '__package_flutter_staggered_grid_view_src_widgets_staggered_grid_tile.dart'
    as l45;
import '__package_path_provider_platform_interface_path_provider_platform_interface.dart'
    as l46;
import '__package_provider_src_async_provider.dart' as l47;
import '__package_provider_src_change_notifier_provider.dart' as l48;
import '__package_provider_src_consumer.dart' as l49;
import '__package_provider_src_listenable_provider.dart' as l50;
import '__package_provider_src_provider.dart' as l51;
import '__package_provider_src_proxy_provider.dart' as l52;
import '__package_provider_src_reassemble_handler.dart' as l53;
import '__package_provider_src_selector.dart' as l54;
import '__package_provider_src_value_listenable_provider.dart' as l55;
import '__package_material_color_utilities_blend_blend.dart' as l56;
import '__package_material_color_utilities_hct_cam16.dart' as l57;
import '__package_material_color_utilities_hct_hct.dart' as l58;
import '__package_material_color_utilities_hct_viewing_conditions.dart' as l59;
import '__package_material_color_utilities_palettes_core_palette.dart' as l60;
import '__package_material_color_utilities_palettes_tonal_palette.dart' as l61;
import '__package_material_color_utilities_quantize_quantizer.dart' as l62;
import '__package_material_color_utilities_quantize_quantizer_celebi.dart'
    as l63;
import '__package_material_color_utilities_quantize_quantizer_map.dart' as l64;
import '__package_material_color_utilities_quantize_quantizer_wsmeans.dart'
    as l65;
import '__package_material_color_utilities_quantize_quantizer_wu.dart' as l66;
import '__package_material_color_utilities_scheme_scheme.dart' as l67;
import '__package_material_color_utilities_score_score.dart' as l68;
import '__package_characters_src_characters.dart' as l69;
import '__package_characters_src_extensions.dart' as l70;
import '__package_meta_meta_meta.dart' as l71;
import '__package_collection_collection.dart' as l72;
import '__package_flutter_localizations_src_cupertino_localizations.dart'
    as l73;
import '__package_flutter_localizations_src_l10n_generated_cupertino_localizations.dart'
    as l74;
import '__package_flutter_localizations_src_l10n_generated_material_localizations.dart'
    as l75;
import '__package_flutter_localizations_src_l10n_generated_widgets_localizations.dart'
    as l76;
import '__package_flutter_localizations_src_material_localizations.dart' as l77;
import '__package_flutter_localizations_src_widgets_localizations.dart' as l78;
import '__package_intl_src_global_state.dart' as l79;
import '__package_intl_src_intl_date_format.dart' as l80;
import '__package_intl_src_intl_helpers.dart' as l81;
import '__package_intl_src_plural_rules.dart' as l82;
import '__package_intl_src_intl_bidi.dart' as l83;
import '__package_intl_src_intl_bidi_formatter.dart' as l84;
import '__package_intl_src_intl_micro_money.dart' as l85;
import '__package_intl_src_intl_number_format.dart' as l86;
import '__package_intl_src_intl_text_direction.dart' as l87;
import '__package_dual_screen_src_dual_screen_info.dart' as l88;
import '__package_dual_screen_src_two_pane.dart' as l89;
import '__package_dual_screen_src_media_query_extension.dart' as l90;
import '__package_url_launcher_platform_interface_url_launcher_platform_interface.dart'
    as l91;
import '__package_url_launcher_url_launcher_string.dart' as l92;
import '__package_url_launcher_src_type_conversion.dart' as l93;
import '__package_flutter_staggered_grid_view_src_foundation_extensions.dart'
    as l94;
import '__package_flutter_staggered_grid_view_src_foundation_constants.dart'
    as l95;
import '__package_flutter_staggered_grid_view_src_layouts_sliver_patterned_grid_delegate.dart'
    as l96;
import '__package_flutter_staggered_grid_view_src_widgets_uniform_track.dart'
    as l97;
import '__package_flutter_staggered_grid_view_src_rendering_staggered_grid.dart'
    as l98;
import '__package_plugin_platform_interface_plugin_platform_interface.dart'
    as l99;
import '__package_path_provider_platform_interface_src_enums.dart' as l100;
import '__package_path_provider_platform_interface_src_method_channel_path_provider.dart'
    as l101;
import '__package_nested_nested.dart' as l102;
import '__package_material_color_utilities_utils_math_utils.dart' as l103;
import '__package_material_color_utilities_utils_color_utils.dart' as l104;
import '__package_material_color_utilities_hct_hct_solver.dart' as l105;
import '__package_material_color_utilities_quantize_point_provider_lab.dart'
    as l106;
import '__package_material_color_utilities_quantize_point_provider.dart'
    as l107;
import '__package_characters_src_characters_impl.dart' as l108;
import '__package_collection_src_algorithms.dart' as l109;
import '__package_collection_src_boollist.dart' as l110;
import '__package_collection_src_canonicalized_map.dart' as l111;
import '__package_collection_src_combined_wrappers_combined_iterable.dart'
    as l112;
import '__package_collection_src_combined_wrappers_combined_list.dart' as l113;
import '__package_collection_src_combined_wrappers_combined_map.dart' as l114;
import '__package_collection_src_comparators.dart' as l115;
import '__package_collection_src_equality.dart' as l116;
import '__package_collection_src_equality_map.dart' as l117;
import '__package_collection_src_equality_set.dart' as l118;
import '__package_collection_src_functions.dart' as l119;
import '__package_collection_src_iterable_extensions.dart' as l120;
import '__package_collection_src_iterable_zip.dart' as l121;
import '__package_collection_src_list_extensions.dart' as l122;
import '__package_collection_src_priority_queue.dart' as l123;
import '__package_collection_src_queue_list.dart' as l124;
import '__package_collection_src_union_set.dart' as l125;
import '__package_collection_src_union_set_controller.dart' as l126;
import '__package_collection_src_unmodifiable_wrappers.dart' as l127;
import '__package_collection_src_wrappers.dart' as l128;
import '__package_flutter_localizations_src_utils_date_localizations.dart'
    as l129;
import '__package_intl_date_symbols.dart' as l130;
import '__package_intl_src_date_format_internal.dart' as l131;
import '__package_intl_src_intl_constants.dart' as l132;
import '__package_intl_src_intl_date_builder.dart' as l133;
import '__package_intl_src_intl_date_computation.dart' as l134;
import '__package_intl_src_intl_regexp.dart' as l135;
import '__package_intl_src_intl_string_stack.dart' as l136;
import '__package_intl_number_symbols.dart' as l137;
import '__package_intl_number_symbols_data.dart' as l138;
import '__package_intl_src_intl_number_format_parser.dart' as l139;
import '__package_intl_src_intl_number_parser.dart' as l140;
import '__package_url_launcher_platform_interface_src_types.dart' as l141;
import '__package_url_launcher_platform_interface_src_url_launcher_platform.dart'
    as l142;
import '__package_url_launcher_src_url_launcher_string.dart' as l143;
import '__package_flutter_staggered_grid_view_src_rendering_uniform_track.dart'
    as l144;
import '__package_platform_platform.dart' as l145;
import '__package_characters_src_grapheme_clusters_table.dart' as l146;
import '__package_characters_src_grapheme_clusters_constants.dart' as l147;
import '__package_characters_src_grapheme_clusters_breaks.dart' as l148;
import '__package_collection_src_utils.dart' as l149;
import '__package_collection_src_combined_wrappers_combined_iterator.dart'
    as l150;
import '__package_collection_src_empty_unmodifiable_set.dart' as l151;
import '__package_intl_date_symbol_data_custom.dart' as l152;
import '__package_flutter_localizations_src_l10n_generated_date_localizations.dart'
    as l153;
import '__package_clock_clock.dart' as l154;
import '__package_url_launcher_platform_interface_link.dart' as l155;
import '__package_url_launcher_platform_interface_method_channel_url_launcher.dart'
    as l156;
import '__package_platform_src_interface_local_platform.dart' as l157;
import '__package_platform_src_interface_platform.dart' as l158;
import '__package_platform_src_testing_fake_platform.dart' as l159;
import '__package_clock_src_default.dart' as l160;
import '__package_clock_src_clock.dart' as l161;
import '__package_clock_src_stopwatch.dart' as l162;
import '__package_clock_src_utils.dart' as l163;

import '__package_flutter_example_gallery_studies_shrine_model_app_state_model.dart'
    as l164;
import '__package_flutter_example_gallery_studies_shrine_model_product.dart'
    as l165;
import '__package_flutter_example_gallery_studies_shrine_model_products_repository.dart'
    as l166;

import 'package:micro_dart_flutter/generated/micro_dart.dart' as mdf;

const libraryMirrors = <String, m.LibraryMirror>{
  ...mdf.libraryMirrors,
  'package:flutter_example_gallery/main.dart': l1.libraryMirror,
  'package:flutter_example_gallery/all.dart': l2.libraryMirror,
  'package:flutter_example_gallery/gen_l10n/gallery_localizations.dart':
      l3.libraryMirror,
  'package:flutter_example_gallery/data/gallery_options.dart': l4.libraryMirror,
  'package:flutter_example_gallery/pages/splash.dart': l5.libraryMirror,
  'package:flutter_example_gallery/constants.dart': l6.libraryMirror,
  'package:flutter_example_gallery/sdudies/shirine/page_status.dart':
      l7.libraryMirror,
  'package:flutter_example_gallery/sdudies/shirine/supplemental/layout_cache.dart':
      l8.libraryMirror,
  'package:flutter_example_gallery/layout/adaptive.dart': l9.libraryMirror,
  'package:flutter_example_gallery/codeviewer/code_style.dart':
      l10.libraryMirror,
  'package:scoped_model/scoped_model.dart': l11.libraryMirror,
  'package:url_launcher/url_launcher.dart': l12.libraryMirror,
  'package:animations/animations.dart': l13.libraryMirror,
  'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart':
      l14.libraryMirror,
  'package:path_provider/path_provider.dart': l15.libraryMirror,
  'package:provider/provider.dart': l16.libraryMirror,
  'package:vector_math/vector_math_64.dart': l17.libraryMirror,
  'package:material_color_utilities/material_color_utilities.dart':
      l18.libraryMirror,
  'package:characters/characters.dart': l19.libraryMirror,
  'package:meta/meta.dart': l20.libraryMirror,
  'package:flutter_localizations/flutter_localizations.dart': l21.libraryMirror,
  'package:intl/intl.dart': l22.libraryMirror,
  'package:flutter_example_gallery/gen_l10n/gallery_localizations_en.dart':
      l23.libraryMirror,
  'package:flutter_example_gallery/gen_l10n/gallery_localizations_zh.dart':
      l24.libraryMirror,
  'package:dual_screen/dual_screen.dart': l25.libraryMirror,
  'package:url_launcher/src/legacy_api.dart': l26.libraryMirror,
  'package:url_launcher/src/types.dart': l27.libraryMirror,
  'package:url_launcher/src/url_launcher_uri.dart': l28.libraryMirror,
  'package:animations/src/fade_scale_transition.dart': l29.libraryMirror,
  'package:animations/src/fade_through_transition.dart': l30.libraryMirror,
  'package:animations/src/modal.dart': l31.libraryMirror,
  'package:animations/src/open_container.dart': l32.libraryMirror,
  'package:animations/src/page_transition_switcher.dart': l33.libraryMirror,
  'package:animations/src/shared_axis_transition.dart': l34.libraryMirror,
  'package:flutter_staggered_grid_view/src/layouts/quilted.dart':
      l35.libraryMirror,
  'package:flutter_staggered_grid_view/src/layouts/staired.dart':
      l36.libraryMirror,
  'package:flutter_staggered_grid_view/src/layouts/woven.dart':
      l37.libraryMirror,
  'package:flutter_staggered_grid_view/src/rendering/sliver_masonry_grid.dart':
      l38.libraryMirror,
  'package:flutter_staggered_grid_view/src/rendering/sliver_simple_grid_delegate.dart':
      l39.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/aligned_grid_view.dart':
      l40.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/masonry_grid_view.dart':
      l41.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/sliver_aligned_grid.dart':
      l42.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/sliver_masonry_grid.dart':
      l43.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/staggered_grid.dart':
      l44.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/staggered_grid_tile.dart':
      l45.libraryMirror,
  'package:path_provider_platform_interface/path_provider_platform_interface.dart':
      l46.libraryMirror,
  'package:provider/src/async_provider.dart': l47.libraryMirror,
  'package:provider/src/change_notifier_provider.dart': l48.libraryMirror,
  'package:provider/src/consumer.dart': l49.libraryMirror,
  'package:provider/src/listenable_provider.dart': l50.libraryMirror,
  'package:provider/src/provider.dart': l51.libraryMirror,
  'package:provider/src/proxy_provider.dart': l52.libraryMirror,
  'package:provider/src/reassemble_handler.dart': l53.libraryMirror,
  'package:provider/src/selector.dart': l54.libraryMirror,
  'package:provider/src/value_listenable_provider.dart': l55.libraryMirror,
  'package:material_color_utilities/blend/blend.dart': l56.libraryMirror,
  'package:material_color_utilities/hct/cam16.dart': l57.libraryMirror,
  'package:material_color_utilities/hct/hct.dart': l58.libraryMirror,
  'package:material_color_utilities/hct/viewing_conditions.dart':
      l59.libraryMirror,
  'package:material_color_utilities/palettes/core_palette.dart':
      l60.libraryMirror,
  'package:material_color_utilities/palettes/tonal_palette.dart':
      l61.libraryMirror,
  'package:material_color_utilities/quantize/quantizer.dart': l62.libraryMirror,
  'package:material_color_utilities/quantize/quantizer_celebi.dart':
      l63.libraryMirror,
  'package:material_color_utilities/quantize/quantizer_map.dart':
      l64.libraryMirror,
  'package:material_color_utilities/quantize/quantizer_wsmeans.dart':
      l65.libraryMirror,
  'package:material_color_utilities/quantize/quantizer_wu.dart':
      l66.libraryMirror,
  'package:material_color_utilities/scheme/scheme.dart': l67.libraryMirror,
  'package:material_color_utilities/score/score.dart': l68.libraryMirror,
  'package:characters/src/characters.dart': l69.libraryMirror,
  'package:characters/src/extensions.dart': l70.libraryMirror,
  'package:meta/meta_meta.dart': l71.libraryMirror,
  'package:collection/collection.dart': l72.libraryMirror,
  'package:flutter_localizations/src/cupertino_localizations.dart':
      l73.libraryMirror,
  'package:flutter_localizations/src/l10n/generated_cupertino_localizations.dart':
      l74.libraryMirror,
  'package:flutter_localizations/src/l10n/generated_material_localizations.dart':
      l75.libraryMirror,
  'package:flutter_localizations/src/l10n/generated_widgets_localizations.dart':
      l76.libraryMirror,
  'package:flutter_localizations/src/material_localizations.dart':
      l77.libraryMirror,
  'package:flutter_localizations/src/widgets_localizations.dart':
      l78.libraryMirror,
  'package:intl/src/global_state.dart': l79.libraryMirror,
  'package:intl/src/intl/date_format.dart': l80.libraryMirror,
  'package:intl/src/intl_helpers.dart': l81.libraryMirror,
  'package:intl/src/plural_rules.dart': l82.libraryMirror,
  'package:intl/src/intl/bidi.dart': l83.libraryMirror,
  'package:intl/src/intl/bidi_formatter.dart': l84.libraryMirror,
  'package:intl/src/intl/micro_money.dart': l85.libraryMirror,
  'package:intl/src/intl/number_format.dart': l86.libraryMirror,
  'package:intl/src/intl/text_direction.dart': l87.libraryMirror,
  'package:dual_screen/src/dual_screen_info.dart': l88.libraryMirror,
  'package:dual_screen/src/two_pane.dart': l89.libraryMirror,
  'package:dual_screen/src/media_query_extension.dart': l90.libraryMirror,
  'package:url_launcher_platform_interface/url_launcher_platform_interface.dart':
      l91.libraryMirror,
  'package:url_launcher/url_launcher_string.dart': l92.libraryMirror,
  'package:url_launcher/src/type_conversion.dart': l93.libraryMirror,
  'package:flutter_staggered_grid_view/src/foundation/extensions.dart':
      l94.libraryMirror,
  'package:flutter_staggered_grid_view/src/foundation/constants.dart':
      l95.libraryMirror,
  'package:flutter_staggered_grid_view/src/layouts/sliver_patterned_grid_delegate.dart':
      l96.libraryMirror,
  'package:flutter_staggered_grid_view/src/widgets/uniform_track.dart':
      l97.libraryMirror,
  'package:flutter_staggered_grid_view/src/rendering/staggered_grid.dart':
      l98.libraryMirror,
  'package:plugin_platform_interface/plugin_platform_interface.dart':
      l99.libraryMirror,
  'package:path_provider_platform_interface/src/enums.dart': l100.libraryMirror,
  'package:path_provider_platform_interface/src/method_channel_path_provider.dart':
      l101.libraryMirror,
  'package:nested/nested.dart': l102.libraryMirror,
  'package:material_color_utilities/utils/math_utils.dart': l103.libraryMirror,
  'package:material_color_utilities/utils/color_utils.dart': l104.libraryMirror,
  'package:material_color_utilities/hct/hct_solver.dart': l105.libraryMirror,
  'package:material_color_utilities/quantize/point_provider_lab.dart':
      l106.libraryMirror,
  'package:material_color_utilities/quantize/point_provider.dart':
      l107.libraryMirror,
  'package:characters/src/characters_impl.dart': l108.libraryMirror,
  'package:collection/src/algorithms.dart': l109.libraryMirror,
  'package:collection/src/boollist.dart': l110.libraryMirror,
  'package:collection/src/canonicalized_map.dart': l111.libraryMirror,
  'package:collection/src/combined_wrappers/combined_iterable.dart':
      l112.libraryMirror,
  'package:collection/src/combined_wrappers/combined_list.dart':
      l113.libraryMirror,
  'package:collection/src/combined_wrappers/combined_map.dart':
      l114.libraryMirror,
  'package:collection/src/comparators.dart': l115.libraryMirror,
  'package:collection/src/equality.dart': l116.libraryMirror,
  'package:collection/src/equality_map.dart': l117.libraryMirror,
  'package:collection/src/equality_set.dart': l118.libraryMirror,
  'package:collection/src/functions.dart': l119.libraryMirror,
  'package:collection/src/iterable_extensions.dart': l120.libraryMirror,
  'package:collection/src/iterable_zip.dart': l121.libraryMirror,
  'package:collection/src/list_extensions.dart': l122.libraryMirror,
  'package:collection/src/priority_queue.dart': l123.libraryMirror,
  'package:collection/src/queue_list.dart': l124.libraryMirror,
  'package:collection/src/union_set.dart': l125.libraryMirror,
  'package:collection/src/union_set_controller.dart': l126.libraryMirror,
  'package:collection/src/unmodifiable_wrappers.dart': l127.libraryMirror,
  'package:collection/src/wrappers.dart': l128.libraryMirror,
  'package:flutter_localizations/src/utils/date_localizations.dart':
      l129.libraryMirror,
  'package:intl/date_symbols.dart': l130.libraryMirror,
  'package:intl/src/date_format_internal.dart': l131.libraryMirror,
  'package:intl/src/intl/constants.dart': l132.libraryMirror,
  'package:intl/src/intl/date_builder.dart': l133.libraryMirror,
  'package:intl/src/intl/date_computation.dart': l134.libraryMirror,
  'package:intl/src/intl/regexp.dart': l135.libraryMirror,
  'package:intl/src/intl/string_stack.dart': l136.libraryMirror,
  'package:intl/number_symbols.dart': l137.libraryMirror,
  'package:intl/number_symbols_data.dart': l138.libraryMirror,
  'package:intl/src/intl/number_format_parser.dart': l139.libraryMirror,
  'package:intl/src/intl/number_parser.dart': l140.libraryMirror,
  'package:url_launcher_platform_interface/src/types.dart': l141.libraryMirror,
  'package:url_launcher_platform_interface/src/url_launcher_platform.dart':
      l142.libraryMirror,
  'package:url_launcher/src/url_launcher_string.dart': l143.libraryMirror,
  'package:flutter_staggered_grid_view/src/rendering/uniform_track.dart':
      l144.libraryMirror,
  'package:platform/platform.dart': l145.libraryMirror,
  'package:characters/src/grapheme_clusters/table.dart': l146.libraryMirror,
  'package:characters/src/grapheme_clusters/constants.dart': l147.libraryMirror,
  'package:characters/src/grapheme_clusters/breaks.dart': l148.libraryMirror,
  'package:collection/src/utils.dart': l149.libraryMirror,
  'package:collection/src/combined_wrappers/combined_iterator.dart':
      l150.libraryMirror,
  'package:collection/src/empty_unmodifiable_set.dart': l151.libraryMirror,
  'package:intl/date_symbol_data_custom.dart': l152.libraryMirror,
  'package:flutter_localizations/src/l10n/generated_date_localizations.dart':
      l153.libraryMirror,
  'package:clock/clock.dart': l154.libraryMirror,
  'package:url_launcher_platform_interface/link.dart': l155.libraryMirror,
  'package:url_launcher_platform_interface/method_channel_url_launcher.dart':
      l156.libraryMirror,
  'package:platform/src/interface/local_platform.dart': l157.libraryMirror,
  'package:platform/src/interface/platform.dart': l158.libraryMirror,
  'package:platform/src/testing/fake_platform.dart': l159.libraryMirror,
  'package:clock/src/default.dart': l160.libraryMirror,
  'package:clock/src/clock.dart': l161.libraryMirror,
  'package:clock/src/stopwatch.dart': l162.libraryMirror,
  'package:clock/src/utils.dart': l163.libraryMirror,
  'package:flutter_example_gallery/studies/shrine/model/app_state_model.dart':
      l164.libraryMirror,
  'package:flutter_example_gallery/studies/shrine/model/product.dart':
      l165.libraryMirror,
  'package:flutter_example_gallery/studies/shrine/model/products_repository.dart':
      l166.libraryMirror,
};
